name: Downgrade_CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
    KEY_AV: ${{ secrets.KEY_AV }}
    KEY_CG: ${{ secrets.KEY_CG }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.9'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: cjdoris/julia-downgrade-compat-action@v1
        with:
          skip: Pkg, TOML
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1